<?php

namespace RRZE\Settings;

defined('ABSPATH') || exit;

/**
 * Central default configuration.
 *
 * @package RRZE\Settings
 */
class Config
{
    /**
     * Default configuration values.
     *
     * @var array
     */
    protected static $defaults = [
        'options' => [
            'general' => [
                'textdomain_fallback' => 0,
                'disable_welcome_panel' => 0,
                'disable_xmlrpc' => 0,
                'disable_admin_email_verification' => 0,
                'disable_emoji' => 0,
                'disable_google_fonts' => 0,
                'custom_error_page' => 0,
                'white_label' => 0,
                'default_theme' => '',
                'admin_role_threshold_warning' => 0,
                'admin_role_threshold_warning_threshold' => 3,
            ],
            'metatags' => [
                'allow_google_notranslate' => 0,
            ],
            'csp' => [
                'enabled' => '0',
                'default_src' => '\'self\'',
                'script_src' => '\'self\' \'unsafe-inline\'',
                'style_src' => '\'self\' \'unsafe-inline\'',
                'img_src' => '\'self\' data: *.gravatar.com',
                'font_src' => '\'self\' data:',
                'connect_src' => '\'self\'',
                'frame_src' => '\'self\'',
            ],
            'heartbeat' => [
                'disable_frontend' => '0',
                'disable_admin_non_editor' => '0',
                'force_js_slow' => '0',
                'editor_interval' => 15,
                'admin_interval' => 60,
                'role_overrides' => [
                    'administrator' => ['editor' => 15, 'default' => 60],
                    'editor' => ['editor' => 30, 'default' => 90],
                    'author' => ['editor' => 45, 'default' => 120],
                ],
                'admin_allowlist_hooks' => ['index.php'],
            ],
            'media' => [
                'sanitize_filename' => 0,
                'filter_nonimages_mimetypes' => 0,
                'enable_image_resize' => 0,
                'max_width_height' => 2000,
                'enable_sharpen_jpg_images' => 0,
                'enable_svg_support' => 0,
                'enable_filesize_column' => 0,
                'enable_file_replace' => 0,
                'enable_lazy_load' => 0,
                'mime_types' => '',
            ],
            'menus' => [
                'expand_collapse_menus' => 0,
                'menus_custom_column' => 0,
                'menus_custom_fields' => 0,
                'enhanced_menu_search' => 0,
            ],
            'plugins' => [
                'cf7_dequeue' => 0,
                'rrze_newsletter_global_settings' => 0,
                'rrze_newsletter_mail_queue_send_limit' => 15,
                'rrze_newsletter_mail_queue_max_retries' => 1,
                'rrze_newsletter_disable_subscription' => 0,
                'rrze_newsletter_sender_allowed_domains' => '',
                'rrze_newsletter_recipient_allowed_domains' => '',
                'rrze_newsletter_exceptions' => '',
                'cms_workflow_not_allowed_post_types' => '',
                'siteimprove_crawler_ip_addresses' => '',
                'wpseo_disable_metaboxes' => 0,
                'the_seo_framework_activate' => 0,
                'ws_form_license_key' => '',
                'ws_form_action_pdf_license_key' => '',
                'ws_form_not_allowed_field_types' => '',
                'ws_form_exceptions' => '',
                'dip_apiKey' => '',
                'faudir_public_apiKey' => '',
                'bite_api_key' => '',
                'dip_edu_api_key' => '',
                'rrze_search_engine_keys' => '',
                'rrze_search_limit_daily' => null,
                'rrze_search_limit_weekly' => null,
                'rrze_search_limit_monthly' => null,
                'rrze_search_limit_yearly' => null,
                'rrze_webt_api_url' => '',
                'rrze_webt_application_name' => '',
                'rrze_webt_password' => '',
                'rrze_webt_exceptions' => '',
                'rrze_formular_allowedDomains' => '',
                'rrze_directions_openrouteservice_api_key' => '',
                'siteimprove' => [
                    'analytics_jscode' => '',
                ],
            ],
            'rest' => [
                'disabled' => '0',
                'restwhite' => ['oembed'],
                'restnetwork' => [],
                'restpublic' => [],
            ],
            'taxonomies' => [
                'exclude_nosearch_posts' => 0,
                'taxonomy_attachment_document' => 0,
                'taxonomy_attachment_category' => 0,
                'taxonomy_attachment_tag' => 0,
                'taxonomy_page_category' => 0,
                'taxonomy_page_tag' => 0,
            ],
            'tools' => [
                'disable_delete_site' => 0,
                'disable_privacy_options' => 0,
            ],
            'users' => [
                'users_search' => 0,
                'pages_author_role' => 0,
                'super_author_role' => 0,
                'contact_page' => 0,
                'can_view_debug_log' => [],
            ],
            'governance' => [
                'websupport_enabled' => 0,
                'websupport_role_name' => 'Websupport',
                'websupport_users' => [],
            ],
            'crawlers' => [
                'entries' => [],
            ],
            'writing' => [
                'enable_post_lock' => 0,
                'post_lock' => 150,
                'autosave_interval' => 60,
                'sync_autosave' => 0,
                'enable_block_editor' => 0,
                'enable_block_editor_new_sites' => 0,
                'try_enable_block_editor' => 0,
                'enable_classic_editor' => 1,
                'allowed_post_types' => '',
                'themes_exceptions' => '',
                'websites_exceptions' => '',
                'allowed_block_types' => '',
                'disabled_block_types' => '',
                'disable_block_directory_assets' => 1,
                'disable_remote_block_patterns' => 1,
                'disable_openverse_media' => 1,
                'disable_font_library_ui' => 1,
                'disable_code_editor' => 1,
                'disable_block_editor_custom_css' => 0,
                'disable_block_editor_custom_css_themes' => '',
                'code_editor_websites_exceptions' => '',
                'disable_custom_fields_metabox' => 0,
                'deactivated_plugins' => '',
            ],
            'mail' => [
                'sender' => '',
                'allowed_domains' => [],
                'admin_email_exceptions' => '',
            ],
            'discussion' => [
                'default_settings' => 1,
                'disable_avatars' => 0,
            ],
            'advanced' => [
                'frontend_style' => '',
                'backend_style' => '',
                'block_editor_iframe_body_class' => '',
                'block_editor_theme_exceptions' => '',
                'block_editor_auto_theme_classes' => 1,
                'disable_ai_functionality' => 1,
                'hide_ai_connector_page' => 1,
                'disable_font_library_admin' => 1,
                'sentry_mode' => 0,
                'sentry_mode_monitor_deletions' => 0,
            ],
            'posts' => [
                'last_modified_custom_column' => 0,
                'page_list_table_dropdown' => 0,
            ],
        ],
        'crawlers' => [
            'siteimprove' => [
                'title' => 'Siteimprove',
                'user_agent' => 'SiteCheck-sitecrawl by Siteimprove.com',
                'ip_addresses' => [
                    '3.10.81.130/32',
                    '3.13.121.241/32',
                    '3.64.159.177/32',
                    '3.66.44.138/32',
                    '3.66.247.32/32',
                    '3.68.122.244/32',
                    '3.74.111.103/32',
                    '3.96.123.225/32',
                    '3.99.148.250/32',
                    '3.113.133.88/32',
                    '3.123.96.88/32',
                    '3.124.26.114/32',
                    '3.125.99.135/32',
                    '3.125.180.27/32',
                    '3.129.126.175/32',
                    '3.131.226.9/32',
                    '3.133.38.181/32',
                    '3.135.49.180/32',
                    '3.136.111.218/32',
                    '3.138.54.100/32',
                    '3.209.121.100/32',
                    '13.48.47.239/32',
                    '13.48.252.26/32',
                    '13.58.165.213/32',
                    '13.239.96.254/32',
                    '18.116.191.222/32',
                    '18.116.197.208/32',
                    '18.153.103.190/32',
                    '18.157.140.51/32',
                    '18.158.147.154/32',
                    '18.159.218.224/32',
                    '18.162.92.10/32',
                    '18.189.206.159/32',
                    '18.190.68.80/32',
                    '18.192.147.131/32',
                    '18.196.205.2/32',
                    '18.198.120.55/32',
                    '18.216.137.252/32',
                    '18.217.48.160/32',
                    '18.219.35.44/32',
                    '18.223.89.15/32',
                    '18.223.191.8/32',
                    '18.230.72.87/32',
                    '35.78.191.94/32',
                    '35.154.71.109/32',
                    '35.156.240.123/32',
                    '35.157.42.7/32',
                    '35.157.236.87/32',
                    '35.158.180.204/32',
                    '35.177.193.208/32',
                    '35.182.100.126/32',
                    '35.204.24.17/32',
                    '52.4.143.42/32',
                    '52.7.141.1/32',
                    '52.8.3.121/32',
                    '52.8.130.130/32',
                    '52.8.142.166/32',
                    '52.17.221.188/32',
                    '52.20.183.91/32',
                    '52.29.157.54/32',
                    '52.29.165.98/32',
                    '52.33.171.213/32',
                    '52.47.166.84/32',
                    '52.48.230.149/32',
                    '52.49.22.75/32',
                    '52.55.30.145/32',
                    '52.56.184.95/32',
                    '52.57.25.76/32',
                    '52.57.115.155/32',
                    '52.57.167.198/32',
                    '52.58.124.116/32',
                    '52.58.146.230/32',
                    '52.60.34.56/32',
                    '52.62.119.24/32',
                    '52.62.147.245/32',
                    '52.63.141.250/32',
                    '52.63.157.211/32',
                    '52.64.209.168/32',
                    '52.70.218.116/32',
                    '52.71.233.116/32',
                    '52.76.24.207/32',
                    '52.77.4.220/32',
                    '52.78.201.227/32',
                    '52.79.109.89/32',
                    '52.89.228.115/32',
                    '52.192.200.212/32',
                    '52.199.41.160/32',
                    '54.178.161.184/32',
                    '54.193.30.204/32',
                    '54.233.93.223/32',
                    '80.62.246.46/32',
                    '80.62.246.50/32',
                    '88.150.142.65/32',
                    '93.160.60.22/32',
                    '93.160.60.51/32',
                    '149.72.248.150/32',
                    '168.245.125.127/32',
                    '173.45.86.10/32',
                    '173.45.86.74/32',
                    '185.229.144.10/32',
                    '185.229.144.22/32',
                    '185.229.144.61/32',
                    '185.229.145.22/32',
                ],
                'contact_email' => '',
                'contact_url' => 'https://siteimprove.com/bots',
                'notes' => '',
            ],
            'fau-aid-personalhandbuchbot' => [
                'title' => 'FAU-AID PersonalhandbuchBot',
                'user_agent' => 'FAU-AID-PersonalhandbuchBot/1.0 (+https://aid.fau.de/; mailto:ai-test-support@fau.de)',
                'ip_addresses' => [
                    '131.188.35.28/32',
                ],
                'contact_email' => 'ai-test-support@fau.de',
                'contact_url' => 'https://aid.fau.de/',
                'notes' => 'Projekt der FAU AI Accelerators.',
            ],
            'fau-rrze-checkbot' => [
                'title' => 'FAU-RRZE Checkbot',
                'user_agent' => 'FAU-RRZE-Checkbot/1.0 (+https://www.rrze.de;mailto:webmaster@fau.de)',
                'ip_addresses' => [
                    '131.188.0.0/16',
                ],
                'contact_email' => 'webmaster@fau.de',
                'contact_url' => 'https://www.rrze.de',
                'notes' => '',
            ],
        ],
    ];

    /**
     * Get all defaults or one top-level default group.
     *
     * @param string $key
     * @return array
     */
    public static function get(string $key = ''): array
    {
        if ($key === '') {
            return self::$defaults;
        }

        return self::$defaults[$key] ?? [];
    }
}
