name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read plugin version
        id: plugin_version
        run: |
          plugin_file="rrze-settings.php"
          version=$(grep -oP 'Version:\s*\K[0-9]+\.[0-9]+\.[0-9]+' "$plugin_file")
          if [ -z "$version" ]; then
            echo "Version not found in plugin file. Exiting."
            exit 1
          fi

          echo "Current version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Check if tag or release exists
        env:
          version: ${{ env.version }}
        run: |
          if git rev-parse "${{ env.version }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.version }} already exists. Skipping release."
            exit 1
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.version }}
        with:
          tag_name: "${{ env.version }}"
          release_name: "v${{ env.version }}"
          draft: false
          prerelease: false

      - name: Check if Release was Created
        if: steps.create_release.outputs.id == ''
        run: |
          echo "Release creation failed"
          exit 1
          
      - name: Send Matrix notification
        env:
          MATRIX_ACCESS_TOKEN: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          MATRIX_ROOM_ID: "%21wyUpkRsFMDGzzGmxBf%3Afau.de" # HTML-encoded room ID
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://matrix.fau.de/_matrix/client/r0/rooms/${MATRIX_ROOM_ID}/send/m.room.message?access_token=${MATRIX_ACCESS_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{
              \"msgtype\": \"m.text\",
              \"body\": \"New release created for ${GITHUB_REPOSITORY} by ${GITHUB_ACTOR}. 🎉\"
            }")
          if [ "$response" -ne 200 ]; then
            echo "Error: Failed to send notification to Matrix. HTTP status code: $response"
          fi
